version: '3.7'

services:
  reverse-proxy:
    build:
      context: ./f5-buytime-rp
    # image: interestingstorage/buytime-rp:latest
    restart: always
    ports:
      - 80:18080
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./f5-buytime-frontend
      args:
        REACT_APP_TITLE: "BuyTime Online"
        REACT_APP_FAVICON: "favicon_b.ico"
        REACT_APP_COUNTRY_FLAG: "US"
        REACT_APP_MAP_BG: "map.png"
        REACT_APP_META_FROM_URL: "true"
        REACT_APP_GEO_LOCATION_NEAREST_STORE: "api/v2/geo-services/nearest-store/zip"
        REACT_APP_GEO_LOCATION_USER_ZIPSTORES: "api/v2/geo-services/nearest-store/geo"
        REACT_APP_GEO_LOCATION_ZIP_INFO: "api/v2/us-zip"
        REACT_APP_NO_NEAREST_STORE: "false"
    # image: interestingstorage/buytime-frontend:latest
    restart: always
    environment: 
      PORT: 80
    depends_on:
      - backend

  backend:
    build:
      context: ./f5-auction-backend
    # image: interestingstorage/buytime-backend:latest
    restart: always
    environment: 
      MYSQL_HOST: "buytime-database"
      PORT: 80
    depends_on:
      - buytime-database      

  buytime-database:
    build:
      context: ./f5-nearest-store-db
    # image: interestingstorage/buytime-db:latest
    restart: always

  find-a-store-service:
    build:
      context: ./f5-nearest-store-backend
    environment: 
      MYSQL_HOST: "buytime-database"
      MYSQL_DB: store_location
      PORT: 80
    # image: interestingstorage/buytime-find-a-store-service:latest
    restart: always
    depends_on:
      - buytime-database