version: '3.7'

services:
  # au-mysql:
  #   image: mysql:8.0.11
  #   command: mysqld --default-authentication-plugin=mysql_native_password # --init-file /data/application/db-init.sql
  #   #volumes:
  #   #  - ./db-init.sql:/data/application/db-init.sql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}


  demo-mysql:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3306:3306